### ISSUE TITLE
Make DM become HA

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/dm#406]
# Overview

- Make DM become HA, which includes making it tolerant to process crashes, machine failures, network partitioning and more.
- Combine DM-master into DM-worker as one binary file.

### Problem Statement

- The current set of DM cluster has only one DM-master process. When the DM-master process is abnormal, task management, cluster management, and shard DDL coordination can no longer be performed.
- The current set of DM cluster has only one DM-worker process for each upstream MySQL/MariaDB instance. When the DM-worker process is abnormal, data migration related to the upstream MySQL/MariaDB instance is interrupted.
- For some metadata (task configuration, cluster version, etc.), there is only one copy of data locally on the DM-worker node. When the local data copy is damaged, the data migration task is difficult to recover.

### Proposed Solution

- Combine DM-master into DM-worker to reduce cluster components (Let's still call it *DM-worker* below).
- Embed etcd into each DM-worker process as a cluster for storing metadata and leader election.
- Elect a leader for DM-worker instances based on the etcd cluster to handle user requests (from *dmctl* or other HTTP clients, just like the previous *DM-master* did). If the original leader fails, a new leader is automatically elected. Note, the entire DM cluster has at most one leader at a time (Let's call it *leader* below).
- Support deploying one or more DM-worker instances for **each** upstream MySQL/MariaDB instance and electing an instance to run related data migration subtasks. If the original instance fails, a new instance is automatically elected to run the data migration subtasks. Note, for each upstream MySQL/MariaDB instance, at most one DM-worker instance is running the data migration subtasks at the same time. One example:
    - for MySQL-A, two DM-workers (DM-worker-1 and DM-worker-2) exist. Then we need to elect DM-worker-1 or DM-worker-2 to run the subtasks, and we mark the elected DM-worker as the *running* instance and others as *idle* instances.
    - for MySQL-B, only one DM-worker (DM-worker-3) exist. Then we elect DM-worker-3 to run the subtasks.

# Success Criteria

- If multiple DM-worker instances are deployed, user requests can still be handled when no more than half of the instances are abnormal.
- As long as more than half of the DM-worker instances are available, metadata reads and writes are not affected.
- As long as there is one or more available DM-worker instances corresponding to an upstream MySQL/MariaDB instance, the data migration associated with that upstream is not affected.
- Deploying only one DM-worker instance can still handle data migration tasks when there is only one upstream MySQL/MariaDB instance.

# TODO list

- [x]  Embed etcd into each DM-master process as a cluster  for storing metadata and leader election.
    - [x]  Embed etcd into each DM-master process, done in #344.
    - [x]  Join DM-master members into an existing cluster, done in #350.
    - [x]  Elect a leader between DM-master member, done in #367.
- [ ]  Build an API-server or operation queue based on the etcd cluster, partially done in #363.
- [ ]  Elect a DM-worker to run upstream related data migration subtasks, partially done in #399.
- [ ]  Register DM-worker dynamically for specified upstream, partially done in #394.
- [ ]  Combine DM-master and DM-worker into one binary.
    - [ ]  Combine and refine the API-server (including gRPC and HTTP) in DM-master into DM-worker.
    - [ ]  Combine DM-master and DM-worker into one process and refine configuration items.
    - [ ]  Refine subtask management in DM-worker based on new API-server.
    - [ ]  Combine and refine shard DDL coordinator in DM-master into DM-worker (It is acceptable that this is not implemented in this project.)
- [ ]  Reschedule the data migration subtask when the DM-worker is abnormal.

# References

- [DM source code reading](https://pingcap.com/blog-cn/#DM-%E6%BA%90%E7%A0%81%E9%98%85%E8%AF%BB) (Chinese version)
- [DM High Availability Design Document](https://docs.google.com/document/d/139UGpC_kNmmgkLRQuTbFfBz2BBQtjuggSl1uLEXOKRo/) (Chinese version)
- [DM High Availability Minimization Refactoring](https://docs.google.com/document/d/1BsapfVx1qxoyrXuyxIOw6mIdIJ0m1xKDlsVVZWs6lZw/) (Chinese version)
- [Jira Epic about HA minimization refactoring of DM](https://internal.pingcap.net/jira/browse/TOOL-1468) (Only visible internally)

**Comment by Little-Wallace** [comment]
I want to join in this task~

**Comment by nolouch** [comment]
I want to join in this task~

**Comment by GregoryIan** [comment]
@csuzhangxc @nolouch  you can link some discussed conclusion documents here

**Comment by csuzhangxc** [comment]
> @csuzhangxc @nolouch you can link some discussed conclusion documents here, don't be afraid that the document is in Chinese, maybe some companies or communities are interested in it

@GregoryIan I've linked the document in the `Design` section above and updated the TODO list too.
