### ISSUE TITLE
release: v1.0.6

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/dm#737]
Release date: June 17, 2020

- [x] PR merge (ref the [milestone](https://github.com/pingcap/dm/milestone/5))
    - [x] Update the version for DM-Ansible #750
    - [x] Update TiDB parser #750
    - [x] Update terror codes #742
    - [x] Release notes in this repo #749
- [x] Release notes
    - [x] Release notes-eng https://github.com/pingcap/docs-dm/pull/113
    - [x] Release notes-zh_CN https://github.com/pingcap/docs-dm/pull/113
- [x] Git commit hash `eaf2683c05ab44143bfb286bfbbc3ba157c555cc`
- [x] Update docs https://github.com/pingcap/docs-dm/pull/112
- [x] ~~Testing report (N/A)~~
- [x] Close the [milestone](https://github.com/pingcap/dm/milestone/5)
