### ISSUE TITLE
test not stable

### ISSUE THREAD

**Issue by lance6716** [pingcap/dm#773]
record broken test case here

#### Unit test

- [x] testServer.TestTaskAutoResume: https://github.com/pingcap/dm/pull/895

- [x] testForEtcd.TestInfoEtcd: #785 dynamic increase waiting time (by retry)

- [ ] testForEtcd.TestOperationEtcd: #785 dynamic increase waiting time (by retry), [Jenkins outdate]

- [x] testOptimist.testOptimist: #785 dynamic increase waiting time (by retry)

- [x] testMockScheduler: #785 increase lease TTL

- [ ] testForEtcd.TestWorkerKeepAlive (added notes)

- [ ] testMockScheduler (added notes)

- [x] testSubTask.TestPauseAndResumeSubtask: https://github.com/pingcap/dm/pull/805

- [x] testMaster.TestOfflineMember: https://github.com/pingcap/dm/pull/824

- [ ] testForEtcd.TestKeepAliveRevokeLease: [Jenkins outdate]

- [ ] testScheduler.TestRestartScheduler: https://github.com/pingcap/dm/pull/812, [Jenkins outdate]

- [x] testMaster.TestOperateSource: https://github.com/pingcap/dm/pull/883

#### Integration test

- [ ] dmctl_basic: [Jenkins outdate]

- [x] ha_cases: fixed by https://github.com/pingcap/tidb/issues/18456

- [ ] shardddl1 (DM-001 failed): https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6108/pipeline/88

- [x] shardddl1 (Unknown database): https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6133/pipeline/88,
seems nothing error
[dm-filter-out-ddl-error.log](https://github.com/pingcap/dm/files/4985782/dm-grep.log),

- [x] sharding2: #785 dynamic increase waiting time (by retry)

- [ ] shardddl3: [Jenkins outdate]

- [ ] http_apis: [Jenkins outdate]

- [x] sharding: https://github.com/pingcap/dm/pull/871

- [ ] ha: [Jenkins outdate]

- [ ] sequence_sharding: [Jenkins outdate]

- [ ] load_interrupt: [Jenkins outdate]

- [ ] sequence_sharding_optimistic: [Jenkins outdate]

- [x] dmctl_basic: #868

- [ ] dmctl_command: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6047/pipeline/75

- [x] drop_column_with_index: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6106/pipeline/71

- [x] full_mode: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6201/pipeline/71, https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/6253/pipeline/71

**Comment by lance6716** [comment]
some unit tests are not stable

https://github.com/pingcap/dm/pull/779#issuecomment-654020665

**Comment by lance6716** [comment]
sharding2: it's very unlikely that worker started (checked by gRPC port alive) but not been discovered by master (checked by `query-status`), going to add a `sleep`

**Comment by lance6716** [comment]
suspect that relay/syncer sometimes can't discover upstream binlog quickly 🤔

**Comment by GMHDBJD** [comment]
for ha_case falied at [check_sync_diff](https://github.com/pingcap/dm/blob/ed9c483e25b12fa29cbb2982828092c51d3eae3b/tests/ha_cases/run.sh#L75) , here is the full logs
[shell_log.txt](https://github.com/pingcap/dm/files/4889234/shell_log.txt)
[all_log.txt](https://github.com/pingcap/dm/files/4889233/all_log.txt)
It is caused by source1 bound by dm-worker3
here is the dm-worker3 log
[dm-worker3_log.txt](https://github.com/pingcap/dm/files/4889281/dm-worker3_log.txt)


**Notice the tail of dm-worker3's log**
```
[2020-07-07T11:24:33.692Z] [2020/07/07 19:23:23.091 +08:00] [INFO] [syncer.go:1612] [task=test] [unit="binlog replication"] [event=query] [statement="alter table ta add unique key gen_idx(`gen_id`)"] [schema=ha_test] ["last location"="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 3665), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443"] [location="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 3857), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443"]
[2020-07-07T11:24:33.692Z] [2020/07/07 19:23:23.091 +08:00] [INFO] [syncer.go:1629] ["resolve sql"] [task=test] [unit="binlog replication"] [event=query] ["raw statement"="alter table ta add unique key gen_idx(`gen_id`)"] [statements="[\"ALTER TABLE `ha_test`.`ta` ADD UNIQUE `gen_idx`(`gen_id`)\"]"] [schema=ha_test] ["last location"="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 3857), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443"] [location="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 3857), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443"]
[2020-07-07T11:24:33.692Z] [2020/07/07 19:23:23.093 +08:00] [INFO] [syncer.go:1718] ["prepare to handle ddls"] [task=test] [unit="binlog replication"] [event=query] [ddls="[\"ALTER TABLE `ha_test`.`ta` ADD UNIQUE `gen_idx`(`gen_id`)\"]"] ["raw statement"="alter table ta add unique key gen_idx(`gen_id`)"] [location="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 3857), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443"]
[2020-07-07T11:24:33.692Z] [2020/07/07 19:23:23.105 +08:00] [INFO] [syncer.go:1739] ["start to handle ddls in normal mode"] [task=test] [unit="binlog replication"] [event=query] [ddls="[\"ALTER TABLE `ha_test`.`ta` ADD UNIQUE `gen_idx`(`gen_id`)\"]"] ["raw statement"="alter table ta add unique key gen_idx(`gen_id`)"] [location="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 3857), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443"]
[2020-07-07T11:24:33.693Z] [2020/07/07 19:23:23.251 +08:00] [INFO] [syncer.go:1612] [task=test2] [unit="binlog replication"] [event=query] [statement="alter table ta add unique key gen_idx(`gen_id`)"] [schema=ha_test2] ["last location"="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 9190), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443"] [location="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 9384), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443"]
[2020-07-07T11:24:33.693Z] [2020/07/07 19:23:23.251 +08:00] [INFO] [syncer.go:1629] ["resolve sql"] [task=test2] [unit="binlog replication"] [event=query] ["raw statement"="alter table ta add unique key gen_idx(`gen_id`)"] [statements="[\"ALTER TABLE `ha_test2`.`ta` ADD UNIQUE `gen_idx`(`gen_id`)\"]"] [schema=ha_test2] ["last location"="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 9384), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443"] [location="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 9384), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443"]
[2020-07-07T11:24:33.693Z] [2020/07/07 19:23:23.254 +08:00] [INFO] [syncer.go:1718] ["prepare to handle ddls"] [task=test2] [unit="binlog replication"] [event=query] [ddls="[\"ALTER TABLE `ha_test2`.`ta` ADD UNIQUE `gen_idx`(`gen_id`)\"]"] ["raw statement"="alter table ta add unique key gen_idx(`gen_id`)"] [location="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 9384), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443"]
[2020-07-07T11:24:33.693Z] [2020/07/07 19:23:23.265 +08:00] [INFO] [syncer.go:1739] ["start to handle ddls in normal mode"] [task=test2] [unit="binlog replication"] [event=query] [ddls="[\"ALTER TABLE `ha_test2`.`ta` ADD UNIQUE `gen_idx`(`gen_id`)\"]"] ["raw statement"="alter table ta add unique key gen_idx(`gen_id`)"] [location="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 9384), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443"]
[2020-07-07T11:24:33.693Z] [2020/07/07 19:23:49.107 +08:00] [INFO] [syncer.go:2157] ["binlog replication progress"] [task=test] [unit="binlog replication"] ["total binlog size"=4253] ["last binlog size"=0] ["cost time"=30] [bytes/Second=141] ["unsynced binlog size"=7567] ["estimate time to catch up"=53]
[2020-07-07T11:24:33.693Z] [2020/07/07 19:23:49.108 +08:00] [INFO] [syncer.go:2182] ["binlog replication status"] [task=test] [unit="binlog replication"] [total_events=18] [total_tps=0] [tps=0] [master_position="(test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 11232)"] [master_gtid=66313859-c043-11ea-9446-ce53e88b4cbb:1-483] [checkpoint="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 3665), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443(flushed position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 3665), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443)"]
[2020-07-07T11:24:33.693Z] [2020/07/07 19:23:51.443 +08:00] [INFO] [syncer.go:2157] ["binlog replication progress"] [task=test2] [unit="binlog replication"] ["total binlog size"=9780] ["last binlog size"=0] ["cost time"=30] [bytes/Second=326] ["unsynced binlog size"=2042] ["estimate time to catch up"=6]
[2020-07-07T11:24:33.693Z] [2020/07/07 19:23:51.444 +08:00] [INFO] [syncer.go:2182] ["binlog replication status"] [task=test2] [unit="binlog replication"] [total_events=18] [total_tps=0] [tps=0] [master_position="(test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 11232)"] [master_gtid=66313859-c043-11ea-9446-ce53e88b4cbb:1-483] [checkpoint="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 9190), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443(flushed position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 9190), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443)"]
[2020-07-07T11:24:33.693Z] [2020/07/07 19:24:19.108 +08:00] [INFO] [syncer.go:2182] ["binlog replication status"] [task=test] [unit="binlog replication"] [total_events=18] [total_tps=0] [tps=0] [master_position="(test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 11232)"] [master_gtid=66313859-c043-11ea-9446-ce53e88b4cbb:1-483] [checkpoint="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 3665), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443(flushed position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 3665), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443)"]
[2020-07-07T11:24:33.693Z] [2020/07/07 19:24:21.444 +08:00] [INFO] [syncer.go:2182] ["binlog replication status"] [task=test2] [unit="binlog replication"] [total_events=18] [total_tps=0] [tps=0] [master_position="(test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 11232)"] [master_gtid=66313859-c043-11ea-9446-ce53e88b4cbb:1-483] [checkpoint="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 9190), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443(flushed position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 9190), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443)"]
```
The below dlls  block almost 1 minute. 
```
ALTER TABLE `ha_test`.`ta` ADD UNIQUE `gen_idx`(`gen_id`)
```
```
ALTER TABLE `ha_test2`.`ta` ADD UNIQUE `gen_idx`(`gen_id`)
```

**Comment by lance6716** [comment]
> for ha_case falied at [check_sync_diff](https://github.com/pingcap/dm/blob/ed9c483e25b12fa29cbb2982828092c51d3eae3b/tests/ha_cases/run.sh#L75) , here is the full logs
> [shell_log.txt](https://github.com/pingcap/dm/files/4889234/shell_log.txt)
> [all_log.txt](https://github.com/pingcap/dm/files/4889233/all_log.txt)
> It is caused by source1 bound by dm-worker3
> here is the dm-worker3 log
> [dm-worker3_log.txt](https://github.com/pingcap/dm/files/4889281/dm-worker3_log.txt)
> 
> **Notice the tail of dm-worker3's log**
> 
> ```
> [2020-07-07T11:24:33.692Z] [2020/07/07 19:23:23.091 +08:00] [INFO] [syncer.go:1612] [task=test] [unit="binlog replication"] [event=query] [statement="alter table ta add unique key gen_idx(`gen_id`)"] [schema=ha_test] ["last location"="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 3665), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443"] [location="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 3857), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443"]
> [2020-07-07T11:24:33.692Z] [2020/07/07 19:23:23.091 +08:00] [INFO] [syncer.go:1629] ["resolve sql"] [task=test] [unit="binlog replication"] [event=query] ["raw statement"="alter table ta add unique key gen_idx(`gen_id`)"] [statements="[\"ALTER TABLE `ha_test`.`ta` ADD UNIQUE `gen_idx`(`gen_id`)\"]"] [schema=ha_test] ["last location"="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 3857), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443"] [location="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 3857), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443"]
> [2020-07-07T11:24:33.692Z] [2020/07/07 19:23:23.093 +08:00] [INFO] [syncer.go:1718] ["prepare to handle ddls"] [task=test] [unit="binlog replication"] [event=query] [ddls="[\"ALTER TABLE `ha_test`.`ta` ADD UNIQUE `gen_idx`(`gen_id`)\"]"] ["raw statement"="alter table ta add unique key gen_idx(`gen_id`)"] [location="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 3857), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443"]
> [2020-07-07T11:24:33.692Z] [2020/07/07 19:23:23.105 +08:00] [INFO] [syncer.go:1739] ["start to handle ddls in normal mode"] [task=test] [unit="binlog replication"] [event=query] [ddls="[\"ALTER TABLE `ha_test`.`ta` ADD UNIQUE `gen_idx`(`gen_id`)\"]"] ["raw statement"="alter table ta add unique key gen_idx(`gen_id`)"] [location="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 3857), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443"]
> [2020-07-07T11:24:33.693Z] [2020/07/07 19:23:23.251 +08:00] [INFO] [syncer.go:1612] [task=test2] [unit="binlog replication"] [event=query] [statement="alter table ta add unique key gen_idx(`gen_id`)"] [schema=ha_test2] ["last location"="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 9190), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443"] [location="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 9384), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443"]
> [2020-07-07T11:24:33.693Z] [2020/07/07 19:23:23.251 +08:00] [INFO] [syncer.go:1629] ["resolve sql"] [task=test2] [unit="binlog replication"] [event=query] ["raw statement"="alter table ta add unique key gen_idx(`gen_id`)"] [statements="[\"ALTER TABLE `ha_test2`.`ta` ADD UNIQUE `gen_idx`(`gen_id`)\"]"] [schema=ha_test2] ["last location"="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 9384), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443"] [location="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 9384), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443"]
> [2020-07-07T11:24:33.693Z] [2020/07/07 19:23:23.254 +08:00] [INFO] [syncer.go:1718] ["prepare to handle ddls"] [task=test2] [unit="binlog replication"] [event=query] [ddls="[\"ALTER TABLE `ha_test2`.`ta` ADD UNIQUE `gen_idx`(`gen_id`)\"]"] ["raw statement"="alter table ta add unique key gen_idx(`gen_id`)"] [location="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 9384), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443"]
> [2020-07-07T11:24:33.693Z] [2020/07/07 19:23:23.265 +08:00] [INFO] [syncer.go:1739] ["start to handle ddls in normal mode"] [task=test2] [unit="binlog replication"] [event=query] [ddls="[\"ALTER TABLE `ha_test2`.`ta` ADD UNIQUE `gen_idx`(`gen_id`)\"]"] ["raw statement"="alter table ta add unique key gen_idx(`gen_id`)"] [location="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 9384), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443"]
> [2020-07-07T11:24:33.693Z] [2020/07/07 19:23:49.107 +08:00] [INFO] [syncer.go:2157] ["binlog replication progress"] [task=test] [unit="binlog replication"] ["total binlog size"=4253] ["last binlog size"=0] ["cost time"=30] [bytes/Second=141] ["unsynced binlog size"=7567] ["estimate time to catch up"=53]
> [2020-07-07T11:24:33.693Z] [2020/07/07 19:23:49.108 +08:00] [INFO] [syncer.go:2182] ["binlog replication status"] [task=test] [unit="binlog replication"] [total_events=18] [total_tps=0] [tps=0] [master_position="(test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 11232)"] [master_gtid=66313859-c043-11ea-9446-ce53e88b4cbb:1-483] [checkpoint="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 3665), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443(flushed position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 3665), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443)"]
> [2020-07-07T11:24:33.693Z] [2020/07/07 19:23:51.443 +08:00] [INFO] [syncer.go:2157] ["binlog replication progress"] [task=test2] [unit="binlog replication"] ["total binlog size"=9780] ["last binlog size"=0] ["cost time"=30] [bytes/Second=326] ["unsynced binlog size"=2042] ["estimate time to catch up"=6]
> [2020-07-07T11:24:33.693Z] [2020/07/07 19:23:51.444 +08:00] [INFO] [syncer.go:2182] ["binlog replication status"] [task=test2] [unit="binlog replication"] [total_events=18] [total_tps=0] [tps=0] [master_position="(test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 11232)"] [master_gtid=66313859-c043-11ea-9446-ce53e88b4cbb:1-483] [checkpoint="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 9190), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443(flushed position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 9190), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443)"]
> [2020-07-07T11:24:33.693Z] [2020/07/07 19:24:19.108 +08:00] [INFO] [syncer.go:2182] ["binlog replication status"] [task=test] [unit="binlog replication"] [total_events=18] [total_tps=0] [tps=0] [master_position="(test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 11232)"] [master_gtid=66313859-c043-11ea-9446-ce53e88b4cbb:1-483] [checkpoint="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 3665), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443(flushed position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 3665), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443)"]
> [2020-07-07T11:24:33.693Z] [2020/07/07 19:24:21.444 +08:00] [INFO] [syncer.go:2182] ["binlog replication status"] [task=test2] [unit="binlog replication"] [total_events=18] [total_tps=0] [tps=0] [master_position="(test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 11232)"] [master_gtid=66313859-c043-11ea-9446-ce53e88b4cbb:1-483] [checkpoint="position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 9190), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443(flushed position: (test-3c3981a5-f648-4ff9-9b2f-324fa0ce4ecf-rmsdt-2h408-bin.000008, 9190), gtid-set: 66313859-c043-11ea-9446-ce53e88b4cbb:1-443)"]
> ```
> 
> The below dlls block almost 1 minute.
> 
> ```
> ALTER TABLE `ha_test`.`ta` ADD UNIQUE `gen_idx`(`gen_id`)
> ```
> 
> ```
> ALTER TABLE `ha_test2`.`ta` ADD UNIQUE `gen_idx`(`gen_id`)
> ```

topic irrelevent: how did you get these logs? I don't know how to login into CI's filesystem. and how to upload to github.com/<project>/files?

**Comment by GMHDBJD** [comment]
> topic irrelevent: how did you get these logs? I don't know how to login into CI's filesystem. and how to upload to github.com//files?
you can click here to cat all logs for masters and workers
![image](https://user-images.githubusercontent.com/35025882/86896017-e8201480-c137-11ea-9cc4-99fd15b35b52.png)

**Comment by lance6716** [comment]
testMaster.TestOfflineMember: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/5615/pipeline/70

after merging master (include #787), `testMaster.TestOfflineMember` still fails. "DM usability improvement" indicates "implement more auto-retry", so we may implement retry on leader connection lost and check if test pass (also improve usability) @WangXiangUSTC

**Comment by lance6716** [comment]
close this because most of failure is either fixed or outdated
