### ISSUE TITLE
Make config file better.

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/dm#775]
## Feature Request

**Is your feature request related to a problem? Please describe:**

In DM, configuration items can be divided into three categories:
   1. Process configuration, such as addr, port, log level, etc
   2. Upstream MySQL related configuration, such as MySQL connection information, source-id, etc
   3. Data migration task configuration, such as task-related upstream and downstream information, block and allow list and other feature related configuration

Currently, the third type information needs to refer to the second type information (for example, the source-id needs to be specified in task.yaml).

**Describe the feature you'd like:**

- Minimize the reference relationship between configuration item categories
- Use Web UI to config easily
- More clear documentation instructions for easy and correct use
- Better checking mechanism to avoid misuse

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lance6716** [comment]
perhaps we should rename these configurations items to let name indicate usage, for example:

mydumpers -> full-data-dump

loaders -> full-data-load

syncer -> incremental-data-sync

**Comment by csuzhangxc** [comment]
> perhaps we should rename these configurations items to let name indicate usage, for example:
> 
> mydumpers -> full-data-dump
> 
> loaders -> full-data-load
> 
> syncer -> incremental-data-sync

`syncer` we are renaming it to `binlog replication` as we did in Grafana dashboard.

**Comment by GMHDBJD** [comment]
- [x] support both task-name and task-file for some command. #854 #855 
- [x] change source config file format to yaml(same as task config file) #828 
- [x] add print-sample-config flag for source config #827 
- [x] check primary/unique key exists in precheck [tidb-tools#376](https://github.com/pingcap/tidb-tools/pull/376)
